title: TABConf 6
logo: /assets/img/nogood/512x512/tabconf6logoyellow512x512.png
description: A Technical Bitcoin Conference
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
